ARG BUILDER=forumi0721/alpine-base:latest

FROM ${BUILDER} as builder

LABEL maintainer="forumi0721@gmail.com"

ENV TARGET_ARCH=aarch64

COPY local/. /usr/local/

#COPY --from=qemu /output/qemu-static /usr/local/bin

RUN ["docker-init"]



FROM scratch

LABEL maintainer="forumi0721@gmail.com"

COPY --from=builder /build/dist/dist-alpine-aarch64 /

RUN ["docker-build-start"]

RUN ["docker-init"]

RUN ["docker-build-end"]

ENTRYPOINT ["docker-run"]

