ARG BASE_TAG=x64
FROM forumi0721/test:${BASE_TAG} as builder
#FROM forumi0721/alpine-base:aarch64 as builder

LABEL maintainer="forumi0721@gmail.com"

ARG BUILD_TAG=armv7

COPY local/bin/docker-build /usr/local/bin/
COPY imagex.sh /usr/local/bin/

RUN ["docker-build"]



FROM forumi0721/scratch:armv7

LABEL maintainer="forumi0721@gmail.com"

COPY --from=builder /output/. /

ENTRYPOINT ["docker-run"]

